CREATE DATABASE IF NOT EXISTS payDB;
USE payDB;

CREATE TABLE IF NOT EXISTS payments (
    PAYID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    AMOUNT VARCHAR(50) NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    PRIMARY KEY (PAYID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE payments AUTO_INCREMENT = 1;

INSERT INTO payments (AMOUNT, STATUS) VALUES
    ('500000', 'REQUEST'),
    ('787878', 'WAITING'),
    ('787878', 'TIMEOUT'),
    ('123456', 'FAILED'),
    ('523456', 'COMPLETED');
